package <%-servicePackage%>;

import <%-apiPackage%>.*;
<%if(hasModel){-%>
import <%-modelPackage%>.*;
<% } -%>
import it.water.core.api.permission.SecurityContext;
import it.water.core.api.registry.ComponentRegistry;
import it.water.core.interceptors.annotations.*;
<% if(applicationTypeEntity) { -%>
import it.water.repository.service.BaseEntityServiceImpl;
<% } else {-%>
import it.water.core.service.BaseServiceImpl;
<% } -%>
import lombok.*;

<% 
let extendsStr = (applicationTypeEntity)?"BaseEntityServiceImpl<"+modelName+">":"BaseServiceImpl";
-%>

/**
 * @Generated by Water Generator
 * Service Api Class for <%- modelName %> entity.
 *
 */
@FrameworkComponent
public class <%- modelName %>ServiceImpl extends <%-extendsStr%> implements <%- modelName %>Api {

    @Inject
    @Getter
    @Setter
    private <%- modelName %>SystemApi systemService;

    @Inject
    @Getter
    @Setter
    private ComponentRegistry componentRegistry;

    public <%- modelName %>ServiceImpl() {
<% if(applicationTypeEntity) { -%>        
        super(<%- modelName %>.class);
<% } -%>
    }
    
    //todo: add custom logic here...
    //use getLog to retrieve Logger instance automatically instantiated for this class
}
