package <%-servicePackage%>;

import <%-apiPackage%>.*;
<%if(hasModel){-%>
import <%-modelPackage%>.*;
<% } -%>
import it.water.core.api.registry.filter.ComponentFilterBuilder;
import it.water.core.interceptors.annotations.*;

<% if(applicationTypeEntity) { -%>
import it.water.repository.service.BaseEntitySystemServiceImpl;
<% } else { -%>
import it.water.core.service.BaseSystemServiceImpl;
<% } -%>

import lombok.*;

<% 
let extendsStr = (applicationTypeEntity)?"BaseEntitySystemServiceImpl<"+modelName+">":"BaseSystemServiceImpl";
-%>

/**
 * @Generated by Water Generator
 * System Service Api Class for <%- modelName %> entity.
 *
 */
@FrameworkComponent
public class <%- modelName %>SystemServiceImpl extends <%-extendsStr%> implements <%- modelName %>SystemApi {
<%if(applicationTypeEntity){ -%>
    @Inject
    @Getter
    @Setter
    private <%- modelName %>Repository repository;

    @Inject
    @Setter
    private ComponentFilterBuilder componentFilterBuilder;

    public <%- modelName %>SystemServiceImpl() {
        super(<%- modelName %>.class);
    }
<% } -%>
    //todo: add custom logic here...

    //1. use getLog to retrieve Logger instance automatically instantiated for this class
    //2. Use componentFilterBuilder, if needed, in order to create filters to retrieve components from the service registry

}