package <%-repositoryPackage%>;

import <%-apiPackage%>.*;
import <%-modelPackage%>.*;
import it.water.core.interceptors.annotations.*;
import it.water.repository.jpa.BaseJpaRepositoryImpl;

/**
 * @Generated by Water Generator
 * Repository Class for <%- modelName %> entity.
 *
 */
@FrameworkComponent
public class <%- modelName %>RepositoryImpl extends BaseJpaRepositoryImpl<<%- modelName %>> implements <%- modelName %>Repository {
    
    public <%- modelName %>RepositoryImpl() {
        super(<%- modelName %>.class);
    }

    //todo: add custom logic here...
    //use method getEntityManager to retrieve JPA Entity manager.
    //use getLog to retrieve Logger instance automatically instantiated for this class

}
