
package <%-serviceRestPackage%>;

import <%-apiPackage%>.*;
import <%-apiPackage%>.rest.*;
<%if(hasModel){-%>
import <%-modelPackage%>.*;
<% } -%>

import it.water.core.api.model.PaginableResult;

import lombok.*;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.http.ResponseEntity;
<% if(applicationTypeEntity) {-%>
import it.water.service.rest.persistence.BaseEntityRestApi;
import org.springframework.transaction.annotation.Transactional;
<% } -%>

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
<%
    let extendsDeclaration = "";
    if(applicationTypeEntity){
        extendsDeclaration = "extends BaseEntityRestApi<"+modelName+">";
    }

-%>
/**
 * @Generated by Water Generator
 * Rest Api Class for <%- modelName %> entity.
 *
 */
@RestController
<%if(applicationTypeEntity){-%>
@Transactional
<% } -%>
public class <%- modelName %>RestControllerImpl <%-extendsDeclaration%> implements <%- modelName %>RestApi {
    @SuppressWarnings("java:S1068") //still mantain the variable even if not used
    private static Logger log = LoggerFactory.getLogger(<%- modelName %>RestControllerImpl.class.getName());

    @Autowired
    @Getter
    private <%- modelName %>Api entityService;

<%if(applicationTypeEntity){-%>
    //All CRUD methods are already exposed by BaseEntitytRestApi. Here all methods are wrapped in order to support spring standard
    //if you need to check which methods are exposed please go to <%-apiPackage%>.rest.<%- modelName %>
    @Override
    @SuppressWarnings("java:S1185") //disabling sonar because spring needs to override this method
    public ResponseEntity<<%- modelName %>> saveApi(<%- modelName %> entity) {
        return ResponseEntity.ok(super.save(entity));
    }

    @Override
    @SuppressWarnings("java:S1185") //disabling sonar because spring needs to override this method
    public ResponseEntity<<%- modelName %>> updateApi(<%- modelName %> entity) {
        return ResponseEntity.ok(super.update(entity));
    }

    @Override
    @SuppressWarnings("java:S1185") //disabling sonar because spring needs to override this method
    public ResponseEntity<<%- modelName %>> findApi(long id) {
        return ResponseEntity.ok(super.find(id));
    }

    @Override
    @SuppressWarnings("java:S1185") //disabling sonar because spring needs to override this method
    public ResponseEntity<PaginableResult<<%- modelName %>>> findAllApi() {
        return ResponseEntity.ok(super.findAll());
    }

    @Override
    @SuppressWarnings("java:S1185") //disabling sonar because spring needs to override this method
    public ResponseEntity<<%- modelName %>> removeApi(long id) {
        super.remove(id);
        return ResponseEntity.status(204).build();
    }
<% } -%>
    //todo add custom exposed methods or override CRUD operations
    //ATTENTION: use always <%- modelName %>Api object in order to ensure the user is requesting operations has the right privileges to do it
}
