package <%-servicePackage%>;

import <%-apiPackage%>.*;
import <%-modelPackage%>.*;
import it.water.core.api.permission.SecurityContext;
import it.water.core.api.registry.ComponentRegistry;

import it.water.repository.service.BaseEntityServiceImpl;

import lombok.*;

import org.osgi.service.cdi.annotations.Bean;
import org.osgi.service.cdi.annotations.Reference;
import org.osgi.service.cdi.annotations.Service;
import org.osgi.service.cdi.annotations.SingleComponent;

import javax.inject.Inject;

/**
 * @Generated by Water Generator
 * Service Api Class for <%- projectSuffixUpperCase %> entity.
 *
 */
@SingleComponent
@Bean
@Service(value = <%- projectSuffixUpperCase %>Api.class)
public class <%- projectSuffixUpperCase %>ServiceImpl extends BaseEntityServiceImpl<<%- projectSuffixUpperCase %>> implements <%- projectSuffixUpperCase %>Api {

    @Getter
    @Setter
    @Reference
    @Inject
    private <%- projectSuffixUpperCase %>SystemApi systemService;

    @Getter
    @Setter
    @Reference
    @Inject
    private ComponentRegistry componentRegistry;

    public <%- projectSuffixUpperCase %>ServiceImpl() {
        super(<%- projectSuffixUpperCase %>.class);
    }

    @Override
    protected SecurityContext getSecurityContext() {
        return null;
    }

    //todo: add custom logic here...
    //use getLog to retrieve Logger instance automatically instantiated for this class
}
