package <%-servicePackage%>;

import <%-apiPackage%>.*;
import <%-modelPackage%>.*;
import it.water.core.api.registry.filter.ComponentFilterBuilder;

import it.water.repository.service.BaseEntitySystemServiceImpl;

import org.osgi.service.cdi.annotations.Bean;
import org.osgi.service.cdi.annotations.Reference;
import org.osgi.service.cdi.annotations.Service;
import org.osgi.service.cdi.annotations.SingleComponent;

import lombok.*;

import javax.inject.Inject;

/**
 * @Generated by Water Generator
 * System Service Api Class for <%- projectSuffixUpperCase %> entity.
 *
 */
@SingleComponent
@Bean
@Service(value = <%- projectSuffixUpperCase %>SystemApi.class)
public class <%- projectSuffixUpperCase %>SystemServiceImpl extends BaseEntitySystemServiceImpl< <%- projectSuffixUpperCase %>> implements <%- projectSuffixUpperCase %>SystemApi {

    @Getter
    @Setter
    @Reference
    @Inject
    private <%- projectSuffixUpperCase %>Repository repository;

    @Getter
    @Setter
    @Reference
    @Inject
    private ComponentFilterBuilder componentFilterBuilder;

    public <%- projectSuffixUpperCase %>SystemServiceImpl() {
        super(<%- projectSuffixUpperCase %>.class);
    }

    //todo: add custom logic here...

    //1. use getLog to retrieve Logger instance automatically instantiated for this class
    //2. Use componentFilterBuilder, if needed, in order to create filters to retrieve components from the service registry

}