package <%-servicePackage%>;

import <%-apiPackage%>.*;
<%if(hasModel){-%>
import <%-modelPackage%>.*;
<% } -%>
import it.water.core.api.permission.SecurityContext;
import it.water.core.api.registry.ComponentRegistry;
import it.water.core.api.service.BaseEntitySystemApi;
import it.water.core.interceptors.annotations.*;
<% if(applicationTypeEntity) { -%>
import it.water.repository.service.BaseEntityServiceImpl;
<% } else {-%>
import it.water.core.service.BaseServiceImpl;
<% } -%>

import lombok.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

<% 
let extendsStr = (applicationTypeEntity)?"BaseEntityServiceImpl<"+modelName+">":"BaseServiceImpl";
-%>

/**
 * @Generated by Water Generator
 * Service Api Class for <%- modelName %> entity.
 *
 */
@Service
public class <%- modelName %>ServiceImpl extends <%-extendsStr%> implements <%- modelName %>Api {

    @Autowired
    @Getter
    private <%- modelName %>SystemApi systemService;

    @Autowired
    @Getter
    private ComponentRegistry componentRegistry;

    public <%- modelName %>ServiceImpl() {
<% if(applicationTypeEntity) { -%>        
        super(<%- modelName %>.class);
<% } -%>
    }

    //todo: add custom logic here...
    //use getLog to retrieve Logger instance automatically instantiated for this class
}
