package <%-repositoryPackage%>;

import <%-apiPackage%>.*;
import <%-modelPackage%>.*;
import it.water.core.interceptors.annotations.*;
import it.water.repository.jpa.WaterJpaRepositoryImpl;

/**
 * @Generated by Water Generator
 * Repository Class for <%- modelName %> entity.
 *
 */
@FrameworkComponent
public class <%- modelName %>RepositoryImpl extends WaterJpaRepositoryImpl<<%- modelName %>> implements <%- modelName %>Repository {
    
    private static final String <%- modelName.toUpperCase() %>_PERSISTENCE_UNIT = "<%-modelNameLowerCase%>-persistence-unit";

    public <%- modelName %>RepositoryImpl() {
        super(<%- modelName %>.class,<%- modelName.toUpperCase() %>_PERSISTENCE_UNIT);
    }

    //todo: add custom logic here...
    //use method getEntityManager to retrieve JPA Entity manager.
    //use getLog to retrieve Logger instance automatically instantiated for this class

}
