package <%- apiPackage %>;

import it.water.core.api.repository.BaseRepository;
import <%- modelPackage %>.<%-projectSuffixUpperCase %>;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * @Generated by Water Generator
 * Interface component for <%- projectSuffixUpperCase %> Repository.
 * It is used for CRUD operations, and to interact with the persistence layer.
 *
 */
@Repository
public interface <%- projectSuffixUpperCase %>Repository extends JpaRepository<<%- projectSuffixUpperCase %>, Long>, BaseRepository<<%- projectSuffixUpperCase %>> {
	
}
