
package <%-serviceRestPackage%>;

import <%-apiPackage%>.*;
import <%-apiPackage%>.rest.*;
<%if(hasModel){-%>
import <%-modelPackage%>.*;
<% } -%>
import it.water.service.rest.persistence.BaseEntityRestApi;
import it.water.core.interceptors.annotations.Inject;
import it.water.core.api.model.PaginableResult;
import it.water.core.api.service.rest.FrameworkRestController;

import lombok.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
<%
    let extendsDeclaration = "";
    if(applicationTypeEntity){
        extendsDeclaration = "extends BaseEntityRestApi<"+modelName+">";
    }

-%>
/**
 * @Generated by Water Generator
 * Rest Api Class for <%- projectSuffixUpperCase %> entity.
 *
 */
@FrameworkRestController(referredRestApi = <%- modelName %>RestApi.class)
public class <%- modelName %>RestControllerImpl <%-extendsDeclaration%> implements <%- modelName %>RestApi {
    private static Logger log = LoggerFactory.getLogger(<%- modelName %>RestControllerImpl.class.getName());

    @Inject
    @Getter
    @Setter
    private <%- modelName %>Api entityService;

    //todo add custom exposed methods or override CRUD operations
    //ATTENTION: use always <%- projectSuffixLowerCase %>Api object in order to ensure the user is requesting operations has the right privileges to do it
}
