package <%- apiPackage %>;

import it.water.core.api.service.BaseEntityApi;

import <%- modelPackage %>.<%- modelName %>;

/**
 * @Generated by Water Generator
 * This interface defines the externally exposed methods for the entity and allows interaction with it through a permission system.
 *
 */
public interface <%- modelName %>Api extends BaseEntityApi<<%- modelName %>> {

}