package <%- apiPackage %>;

import it.water.core.api.repository.BaseRepository;
import it.water.core.interceptors.annotations.*;
import <%- modelPackage %>.<%-modelName %>;

/**
 * @Generated by Water Generator
 * Interface component for <%- modelName %> Repository.
 * It is used for CRUD operations, and to interact with the persistence layer.
 *
 */
public interface <%- modelName %>Repository extends BaseRepository<<%- modelName %>> {
	
}
