package <%- apiPackage %>;

import it.water.core.api.service.BaseApi;

/**
 * @Generated by Water Generator
 * This interface defines the externally exposed methods and allows interaction with them through a permission system.
 *
 */
public interface <%- modelName %>Api extends BaseApi {

}