package <%- apiPackage %>;

import it.water.core.api.service.BaseSystemApi;

/**
 * 
 * @Generated by Water Generator
 * This interface defines the internally exposed methods allows interaction with them bypassing permission system.
 * 
 */
public interface <%- modelName %>SystemApi extends BaseSystemApi {

}