package <%- apiPackage %>;

import it.water.core.api.repository.BaseRepository;
import <%- modelPackage %>.<%-modelName %>;
import it.water.repository.jpa.spring.SpringBaseJpaRepositoryImpl;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * @Generated by Water Generator
 * Interface component for <%- modelName %> Repository.
 * It is used for CRUD operations, and to interact with the persistence layer.
 *
 */
<% if(springRepository){ -%>
@Repository
<% } -%>
public interface <%- modelName %>Repository extends JpaRepository<<%- modelName %>, Long>, BaseRepository<<%- modelName %>> {
	
}
