package <%- apiPackage %>.rest;


import <%-modelPackage%>.*;

import it.water.core.api.model.PaginableResult;
import it.water.core.api.service.rest.FrameworkRestApi;
import it.water.core.api.service.rest.RestApi;

import com.fasterxml.jackson.annotation.JsonView;
import it.water.service.rest.api.WaterJsonView;
import io.swagger.annotations.Api;
import javax.ws.rs.*;
import javax.ws.rs.core.MediaType;

/**
 * @Generated by Water Generator
 * Rest Api Interface for <%- projectSuffixUpperCase %> entity.
 * This interfaces exposes all CRUD methods with Spring annotations.
 *
 */
@RequestMapping("/<%- restContextRoot %>")
@Api(produces = MediaType.APPLICATION_JSON, tags = "<%- projectSuffixUpperCase %> API")
public interface <%- projectSuffixUpperCase %>RestApi extends RestApi {
    
    @LoggedIn
    @PostMapping
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    <%- projectSuffixUpperCase %> save(<%- projectSuffixUpperCase %> <%- projectSuffixLowerCase %>);

    @LoggedIn
    @PutMapping
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    <%- projectSuffixUpperCase %> update(<%- projectSuffixUpperCase %> <%- projectSuffixLowerCase %>);

    @LoggedIn
    @RequestMapping("/{id}")
    @GetMapping
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    <%- projectSuffixUpperCase %> find(@PathVariable("id") long id);

    @LoggedIn
    @GetMapping
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    PaginableResult<<%- projectSuffixUpperCase %>> findAll();

    @LoggedIn
    @RequestMapping("/{id}")
    @DeleteMapping
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    void remove(@PathVariable("id") long id);
}
