package <%- modelPackage %>;

import it.water.repository.jpa.model.AbstractJpaEntity;
import lombok.*;

import <%-persistenceLib%>.persistence.Access;
import <%-persistenceLib%>.persistence.AccessType;
import <%-persistenceLib%>.persistence.Entity;

/**
 * @Generated by Water Generator
 * <%- projectSuffixUpperCase %> Entity Class.
 *
 */
@Entity
@Access(AccessType.FIELD)
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@Data
@Getter
@Setter
@ToString
public class <%- projectSuffixUpperCase %> extends AbstractJpaEntity {
    //insert fields...

    @Override
    public boolean equals(Object o) {
        //insert logic here
        return false;
    }

    @Override
    public int hashCode() {
        //insert logic here
        return 0;
    }
}