
package <%-projectGroupId%>.spring;

import it.water.core.api.model.PaginableResult;
import it.water.core.api.repository.query.Query;
import it.water.core.api.repository.query.QueryOrder;
import it.water.user.api.rest.spring.UserSpringRestApi;
import it.water.user.model.User;
import it.water.user.service.rest.UserRestControllerImpl;
import org.springframework.web.bind.annotation.RestController;


/**
 * @Generated by Water Generator
 * Rest Api Class for <%- projectSuffixUpperCase %> entity. It just overrides method invoking super in order to let spring find web methods.
 */
@RestController
public class <%- projectSuffixUpperCase %>SpringRestControllerImpl extends <%- projectSuffixUpperCase %>RestControllerImpl implements <%- projectSuffixUpperCase %>SpringRestApi {
    
    @Override
    public <%- projectSuffixUpperCase %> save(<%- projectSuffixUpperCase %> entity) {
        return super.save(entity);
    }

    @Override
    public <%- projectSuffixUpperCase %> update(<%- projectSuffixUpperCase %> entity) {
        return super.update(entity);
    }

    @Override
    public void remove(long id) {
        super.remove(id);
    }

    @Override
    public <%- projectSuffixUpperCase %> find(long id) {
        return super.find(id);
    }

    @Override
    public PaginableResult<<%- projectSuffixUpperCase %>> findAll(Integer delta, Integer page, Query filter, QueryOrder order) {
        return super.findAll(delta, page, filter, order);
    }

    @Override
    public PaginableResult<<%- projectSuffixUpperCase %>> findAll() {
        return super.findAll();
    }
}
