
package <%-servicePackage%>.rest.spring;

import <%-servicePackage%>.rest.<%- modelName %>RestControllerImpl;
import it.water.core.api.model.*;
import it.water.core.api.repository.*;
import it.water.core.api.repository.query.*;
import <%-apiPackage%>.*;
<%if(hasModel){-%>
import <%-modelPackage%>.*;
<%}-%>
import org.springframework.web.bind.annotation.RestController;


/**
 * @Generated by Water Generator
 * Rest Api Class for <%- modelName %> entity. It just overrides method invoking super in order to let spring find web methods.
 */
@RestController
public class <%- modelName %>SpringRestControllerImpl extends <%- modelName %>RestControllerImpl implements <%- modelName %>SpringRestApi {
    <%if(applicationTypeEntity){-%>
    @Override
    @SuppressWarnings("java:S1185") //disabling sonar because spring needs to override this method
    public <%- modelName %> save(<%- modelName %> entity) {
        return super.save(entity);
    }

    @Override
    @SuppressWarnings("java:S1185") //disabling sonar because spring needs to override this method
    public <%- modelName %> update(<%- modelName %> entity) {
        return super.update(entity);
    }

    @Override
    @SuppressWarnings("java:S1185") //disabling sonar because spring needs to override this method
    public void remove(long id) {
        super.remove(id);
    }

    @Override
    @SuppressWarnings("java:S1185") //disabling sonar because spring needs to override this method
    public <%- modelName %> find(long id) {
        return super.find(id);
    }

    @Override
    @SuppressWarnings("java:S1185") //disabling sonar because spring needs to override this method
    public PaginableResult<<%- modelName %>> findAll(Integer delta, Integer page, Query filter, QueryOrder order) {
        return super.findAll(delta, page, filter, order);
    }

    @Override
    @SuppressWarnings("java:S1185") //disabling sonar because spring needs to override this method
    public PaginableResult<<%- modelName %>> findAll() {
        return super.findAll();
    }
    <%}-%>
}
