
package <%-servicePackage%>.rest.spring;

import <%-servicePackage%>.rest.<%- projectSuffixUpperCase %>RestControllerImpl;
import it.water.core.api.model.*;
import it.water.core.api.repository.*;
import it.water.core.api.repository.query.*;
import <%-apiPackage%>.*;
import <%-modelPackage%>.*;
import org.springframework.web.bind.annotation.RestController;


/**
 * @Generated by Water Generator
 * Rest Api Class for <%- projectSuffixUpperCase %> entity. It just overrides method invoking super in order to let spring find web methods.
 */
@RestController
public class <%- projectSuffixUpperCase %>SpringRestControllerImpl extends <%- projectSuffixUpperCase %>RestControllerImpl implements <%- projectSuffixUpperCase %>SpringRestApi {
    
    @Override
    public <%- projectSuffixUpperCase %> save(<%- projectSuffixUpperCase %> entity) {
        return super.save(entity);
    }

    @Override
    public <%- projectSuffixUpperCase %> update(<%- projectSuffixUpperCase %> entity) {
        return super.update(entity);
    }

    @Override
    public void remove(long id) {
        super.remove(id);
    }

    @Override
    public <%- projectSuffixUpperCase %> find(long id) {
        return super.find(id);
    }

    @Override
    public PaginableResult<<%- projectSuffixUpperCase %>> findAll(Integer delta, Integer page, Query filter, QueryOrder order) {
        return super.findAll(delta, page, filter, order);
    }

    @Override
    public PaginableResult<<%- projectSuffixUpperCase %>> findAll() {
        return super.findAll();
    }
}
